[project]
name = "google-gemini-pdf-table-extractor"
version = "0.1.0"
description = "Parse pdf using google gemini"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.15.0",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
]
